# Generated by Django 4.1.7 on 2023-04-17 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.PositiveSmallIntegerField(default=0)),
                ('street', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('postalCode', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'address',
                'ordering': ['country', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('clientType', models.CharField(choices=[('NORMAL', 'normal customer'), ('LOYAL', 'loyal customer'), ('VIP', 'Very Important Customer')], default='NORMAL', max_length=50)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.address')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['lastName', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('site_url', models.URLField(default='')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.address')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=50, unique=True)),
                ('price', models.FloatField(default=0)),
                ('expirationDate', models.DateField(default=datetime.date(2023, 12, 31))),
                ('manufacturingDate', models.DateField(default=django.utils.timezone.now)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/product_photos')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_commerce_app.provider')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['label', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmd', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.product')),
            ],
            options={
                'verbose_name': ('Command Management',),
                'verbose_name_plural': 'Command List',
                'db_table': 'command',
                'ordering': ['-date_cmd'],
                'unique_together': {('client', 'product', 'date_cmd')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='clientProducts',
            field=models.ManyToManyField(through='e_commerce_app.Command', to='e_commerce_app.product'),
        ),
    ]
